name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4.0.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3.12.0
        with:
          java-version: "17"
          distribution: "corretto"

      - name: Compile and test with makefile
        run: make all
